---
abstract: "Format lists of data into columns across the terminal's width"
author:
  - 'Doug Bell <preaction@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::Compile: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-FormatColumns
requires:
  List::MoreUtils: 0.33
  Sub::Exporter: 0.984
  Term::ReadKey: 2.30
version: 0.004
